### PR TITLE
0000-01-02-missnanay.md. 

### PR DESCRIPTION
**Pull request by Mitchel01**
I  add the new branch called my slide

### CODE REVIEW

**Review by missnanay — COMMENTED** [review]
I added the new branch and manage to commit and merge ,my filr

**Comment by missnanay** [comment]
**

**Comment by brianamarie** [comment]
Hi @Mitchel01! 👋🏻 I saw your post in the community forum.

The reason that this is blocked, is because the name of the file isn't correct. This is a really tricky thing to do! I've made a gif that shows going into the "files changed" tab, editing a file, and then changing the name and path of a file. For your file, you won't need to delete anything, just add at the beginning of the name: `_posts/`. Thank you for your patience on this!

edit-file-name

**Review by Mitchel01 — COMMENTED** [review]
I  renamed my file

**Pull request merged**
